### ISSUE TITLE
lib/language_server/build.ex uses Mix.Dep.loaded/1 which has been removed in Elixir 1.9.0-dev

### ISSUE THREAD

**Issue by akappen** [JakeBecker/elixir-ls#155]
### Environment

* Elixir & Erlang versions (elixir --version):
```
Erlang/OTP 21 [erts-10.2.4] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe]

Elixir 1.9.0-dev (6f2dc3b72) (compiled with Erlang/OTP 21)
```

* Operating system:
```
Linux - Kernel 4.18
```

* Client (editor or IDE):
```
VSCode 1.31.1
ElixirLS 0.2.24
```

### Problem Report

I was working on a type related bug in Elixir master (1.9.0-dev) and noticed that the ElixirLS plugin for VSCode was blowing up because it was calling a function that has been removed.

```
an exception was raised:
    ** (UndefinedFunctionError) function Mix.Dep.loaded/1 is undefined or private
        (mix) Mix.Dep.loaded([])
        (language_server) lib/language_server/build.ex:16: anonymous fn/2 in ElixirLS.LanguageServer.Build.build/3
        (stdlib) timer.erl:166: :timer.tc/1
        (language_server) lib/language_server/build.ex:13: anonymous fn/2 in ElixirLS.LanguageServer.Build.build/3
        (kernel) global.erl:430: :global.trans/4
```

The `Mix.Dep` module no longer has a `loaded/1` function. 
https://github.com/elixir-lang/elixir/blob/master/lib/mix/lib/mix/dep.ex

Even though Elixir 1.9 final is probably a long way off, I thought you should be aware of this change.

Thanks for a great language server implementation and the wonderful VSCode plugin!!! It makes my day to day development so much nicer!

:clap: :clap: :clap:

**Comment by akappen** [comment]
Here's the commit that removed `loaded/1`.

https://github.com/elixir-lang/elixir/commit/e15b957a0dc7d8febce087ba5dae6156582e2d84#diff-dc64f0b41c45505f2bfe66987de57aaa

**Comment by JakeBecker** [comment]
Should be fixed now. Thank you!

**Comment by collegeimprovements** [comment]
We still get this issue. Though it just gives error for `mix.exs` file.

**Comment by TheFirstAvenger** [comment]
@JakeBecker Can you please release a new version with this fix?

**Comment by JakeBecker** [comment]
Just released v0.2.25 with the fix. Sorry for the wait!

**Comment by TheFirstAvenger** [comment]
Thanks @jakebecker!
